# Indica a imagem base que vamos utilizar no container
FROM node:22-alpine

# É criado um grupo e um usuário para rodar aplicação, pq criar usuário sem login, permiti que não seja usado o terminal
RUN addgroup api && adduser -S -G api api

# Isso serve para definir o usuário que vai rodar a aplicação
USER api

# Indica o diretório de trabalho, todas as execuções e instalações de dependências seão feitas ai
WORKDIR /api

# Isso cópia as dependências de todos os package*.json no diretório atual, no caso o diretório de api
COPY package*.json /api/

# Isso instala as dependências do projeto que estão no package.json, ignorando as dependências de dev
RUN npm ci --omit=dev

# Isso copia os arquivos que estão no diretório atual
COPY . .

# Isso faz o container ser exposto na porta 3000, server vai rodar nessa porta 
EXPOSE 3000

# Isso serve para especificar o comando a ser executado pelo docker
CMD [ "node", "src/server.js" ]